### ISSUE TITLE
bowsers unusable on 3B+

### ISSUE THREAD

**Issue by sgalke** [raspberrypi/bookworm-feedback#89]
bookworm (32- and 64-bit):
browsers (chromium, firefox) are unusable on RPi 3B, 3B+ and 3A+ , they freeze the machine after ~10 seconds. fresh installed.

**Comment by spl237** [comment]
Are you starting the browsers from the icon on the launcher at the top? That has a bug which was fixed in an update released yesterday - try a sudo apt update / sudo apt full-upgrade and reboot, and see if that helps.

If there is a problem when starting browsers directly from the Internet section of the main menu, that would be a new issue - please report back if that is the case.

**Comment by sgalke** [comment]
updated. quick verified on RPi 3B bookworm 64-bit. 
i did not verify yet on other models, nor 32-bit ... 
thank you.

**Comment by haraldkolb** [comment]
Sorry, but I installed bookworm 64 bit last week on an RIPi 3B+ and the issue is still not solved.
I updated the system to the latest avaliable. But every time I try to start the browser using the taskbar Icon the system freezes. This also happens if a program tries to show its GUI using an URL in the browser.

**Comment by popcornmix** [comment]
This issue was for a specific bug which has been fixed, and the issue is closed.

Your issue is unrelated to this one. It's likely just the RAM requirement for a modern browser rendering modern web sites only increases with time, and a six year old device struggles with that. But if you want to discuss it further, then create a new issue.

**Comment by lurch** [comment]
Anecdotally, the memory usage of browsers on a 32-bit OS is a bit less than on a 64-bit OS, so try that first to see if it helps.
